# This blueprint was generated by TOSCA.py on 2016-04-26 17:10:51.052274

import tosca.context.Context
ctx = tosca.context.Context()
ctx.description = 'This Blueprint installs the nodecellar application on an existing host.\n'
ctx.imports.append(tosca.context.Import('http://www.getcloudify.org/spec/cloudify/3.4m4/types.yaml'))
ctx.imports.append(tosca.context.Import('http://www.getcloudify.org/spec/diamond-plugin/1.3.2/plugin.yaml'))
ctx.imports.append(tosca.context.Import('types/nodecellar.yaml'))
ctx.imports.append(tosca.context.Import('types/simple-types.yaml'))
